### 회원가입

POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
  "email": "hhh@tset.com",
  "password": "testTest12!",
  "passwordConfirm": "testTest12!",
  "name": "김나박이",
  "phoneNumber" : "010-3333-0000"
}